services:
  application-golang:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: dockerhub_user/application-golang:dev
    container_name: application-golang
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - ./:/go/src/app